dist: xenial
language: csharp
solution: GhostSharp.sln
mono: none
dotnet: 2.2.104
before_install:
  - sudo apt-get update
  - sudo apt-get install -y nuget
install:
  - nuget restore GhostSharp.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release GhostSharp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./GhostSharp.Tests/bin/Release/GhostSharp.Tests.dll
