dist: xenial
language: csharp
solution: GhostSharp.sln
mono: none
dotnet: 2.2.104
before_install:
  - sudo apt-get update
  - sudo apt-get install -y nuget
  - sudo apt install -y mono-devel
  - sudo mozroots --import --sync --machine --url "http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt"
  - sudo certmgr -ssl -m https://go.microsoft.com
  - sudo certmgr -ssl -m https://nugetgallery.blob.core.windows.net
  - sudo certmgr -ssl -m https://nuget.org
  - sudo nuget update -self
install:
  - nuget restore GhostSharp.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release GhostSharp.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./GhostSharp.Tests/bin/Release/GhostSharp.Tests.dll
